[package]
name = "notion-integrations"
version = "0.1.0"
edition = "2021"

[dependencies]
notion = "0.5.1"
futures = "0.3.15"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.5", features = ["json"] }
serde_json = "1.0.124"
regex = "1.10.6"
chrono = "0.4.38"

