version: '3.1'

networks:
  "${PROJECT}":

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
