apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: template-monorepo
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: main
          image: //svc/api:api
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          ports:
            - containerPort: 80