apiVersion: v1
kind: Service
metadata:
  namespace: template-monorepo
  name: parser
spec:
  selector:
    app: parser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP